# define a porta que o core backend vai rodar > gateway
server.port=8080

spring.application.name=core-backend

# configurações do banco de dados em memória H2
spring.datasource.url=jdbc:h2:mem:feedbackdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# habilita o console do H2 para vermos o banco no navegador (http://localhost:8080/h2-console - é bom para debug, lembrando que não é recomendado para produção)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# pede ao Spring (JPA/Hibernate) para criar as tabelas automaticamente com base nas entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
